### PR TITLE
Add Sabrina avatar

### PR DESCRIPTION
**Pull request by cmozzati**

### CODE REVIEW

**Review by ogizanagi — APPROVED** [review]
👌

**Review by ogizanagi — CHANGES_REQUESTED** [review]
Wait! Il manque l'update du path dans https://github.com/Elao/elao_/blob/a55b03dfacfcc77b22b7f919b7d59efd2c0fff03/content/member/sludovicdelys.yaml#L13

**Comment by cmozzati** [comment]
@ogizanagi done, merci ! :)

**Review by ogizanagi — APPROVED** [review]
Purfect 🐱

**Pull request merged**
